_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 75
                - 77
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 75
                - 77
            "3":
                - 16
                - 55
            "4": 3.13.1
            "5": 0.20.1
            "6": 4.52.4
            "12": 0.20.1
            "13": darwin-arm64
batch_size:
    value: 16
learning_rate:
    value: 2e-05
max_epochs:
    value: 20
patience:
    value: 3
weight_decay:
    value: 0.01
